//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 项目.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_InOutDepotDetail
    {
        public int IODDID { get; set; }
        public Nullable<int> IODID { get; set; }
        public string ProID { get; set; }
        public Nullable<int> IODDAmount { get; set; }
        public Nullable<decimal> IODDPrice { get; set; }
        public Nullable<decimal> IODDOutPrice { get; set; }
        public string ProName { get; set; }
        public string PTName { get; set; }
        public string PUName { get; set; }
        public string PCName { get; set; }
        public string PSName { get; set; }
        public string DepotID { get; set; }
        public string DepotName { get; set; }
        public Nullable<decimal> IODDMoney { get; set; }
    }
}
